apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 32002
  selector:
    app: my-db 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-db
  labels:
    app: my-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-db
  template:
    metadata:
      labels:
        app: my-db
    spec:
      containers:
      - name: mysql
        image: kbpark9898/mysql_pkb:1.1
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 123
          name: MYSQL_DATABASE
          value: boooardgame
          name: MYSQL_USER
          value: admin
          name: MYSQL_ROOT_HOST
          value: '%'
          name: MYSQL_PASSWORD
          value: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /data/mysql
      volumes:
      - name: mysql-storage
        emptyDir: {}
